=== mbruess1/mb.github.io/dystopia/dystopia.dtd
<!--Proseminar HKI - BSI I, Melanie Brüssel, 6068626, 15.03.2015-->

<!ENTITY % id "id ID #REQUIRED">

<!ELEMENT dystopia (name?, lokalisation, medien+)> 
<!ELEMENT name (#PCDATA)>
<!ELEMENT lokalisation EMPTY>
    <!ATTLIST lokalisation
            url CDATA #IMPLIED
    >
<!ELEMENT medien (medium+)>
<!ATTLIST medien
            art (buch|film) #REQUIRED
    >
<!ELEMENT medium (titel+, bild+, trailer*, mitwirkende, erscheinungsjahr, land, inhalt, länge, fsk?, verfügbarkeit)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT bild EMPTY>
    <!ATTLIST bild
            src CDATA #REQUIRED
            %id;
            alt CDATA #REQUIRED
            beschreibung CDATA #IMPLIED
            cover (ja|nein) #REQUIRED
    >
<!ELEMENT trailer EMPTY>
    <!ATTLIST trailer
            src CDATA #REQUIRED
            %id;
            name CDATA #REQUIRED
            beschreibung CDATA #IMPLIED
            official (ja|nein) #REQUIRED
    >
<!ELEMENT mitwirkende (autor, regie?, cast?)>
<!ELEMENT autor EMPTY>
<!ATTLIST autor
            drehbuch CDATA #IMPLIED
            buch CDATA #IMPLIED
    >
 <!ELEMENT regie (#PCDATA)>
 <!ELEMENT cast (#PCDATA)>
<!ELEMENT erscheinungsjahr (#PCDATA)>
<!ELEMENT land (#PCDATA)>
<!ELEMENT inhalt (#PCDATA)>
<!ELEMENT länge (#PCDATA)>
<!ELEMENT fsk (#PCDATA)>
<!ELEMENT verfügbarkeit (online*)>
    <!ATTLIST verfügbarkeit
            onlineverfügbar (ja|nein) #REQUIRED
    >
<!ELEMENT online (#PCDATA)>
<!ATTLIST online
            quelle CDATA #REQUIRED
    >

=== mbruess1/mb.github.io/dystopia/dystopia.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE dystopia SYSTEM "dystopia.dtd">
<!--Proseminar HKI - BSI I, Melanie Brüssel, 6068626, 15.03.2015-->
<dystopia>
    <lokalisation/>
    <medien art="film">
        <medium>
            <titel>Metropolis</titel>
            <bild
                src="http://ia.media-imdb.com/images/M/MV5BNDAzNTkyODg1MF5BMl5BanBnXkFtZTgwMDA3NDkwMDE@._V1_.jpg"
                id="covermetropolis" alt="metropolis cover" cover="ja"/>
            <bild
                src="https://cdn.jocksandnerds.com/media/W1siZiIsIjIwMTUvMDEvMTUvMTIvMjAvNTUvMjAzLzQuanBnIl0sWyJwIiwidGh1bWIiLCIyMDAweDIwMDBcdTAwM2UiXSxbInAiLCJlbmNvZGUiLCJqcGciLCItcXVhbGl0eSA3NSJdXQ/4.jpg?sha=24d755ead88c5b1e"
                id="citymetropolis" alt="city metropolis" cover="nein"/>
            <bild
                src="https://lh6.googleusercontent.com/-afeDa26GDjE/UVM2kn1p2bI/AAAAAAAAAC0/WYF3AxUDZKM/w707-h398-no/MoC_METROPOLIS_BD_02-1.jpg"
                id="citymetropolis2" alt="city metropolis" cover="nein"/>
            <trailer src="http://www.youtube.com/embed/GrFBId1b8U0" id="trailermetropolis"
                name="metropolis trailer" official="nein"/>
            <mitwirkende>
                <autor drehbuch="Thea von Harbou" buch="Thea von Harbou"/>
                <regie>Fritz Lang</regie>
                <cast>Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rogge, Fritz Rasp, Theodor Loos,
                    Erwin Biswanger, Heinrich George, Brigitte Helm</cast>
            </mitwirkende>
            <erscheinungsjahr>1927</erscheinungsjahr>
            <land>Deutschland</land>
            <inhalt>In der Zukunftsstadt Metropolis führen die Reichen ein großartiges Leben.
                Unterirdisch jedoch schuften die Arbeiter, um dieses Luxusdasein zu ermöglichen.
                Freder (Gustav Fröhlich), der Sohn eines tonangebenden Industriellen (Alfred Abel),
                verliebt sich in die Arbeiterin Maria (Brigitte Helm). Durch sie erfährt er in welch
                Elend die Arbeiter leben. Da entführt Wissenschaftler Rottwang (Rudolf Klein-Rogge)
                Maria und entwickelt eine roboterartige Doppelgängerin, die die Proletarier zur
                Revolution führen soll.</inhalt>
            <länge>153 min</länge>
            <fsk>18</fsk>
            <verfügbarkeit onlineverfügbar="ja">
                <online
                    quelle="https://www.skysnap.de/film/scifi--fantasy/metropolis/99936.html?wkzWAZL01zanpid2006744388839310336"
                    >Snap by Sky</online>
                <online quelle="http://www.youtube.com/embed/Ddkb345QNeI">Youtube</online>
            </verfügbarkeit>
        </medium>
    </medien>
    <medien art="film">
        <medium>
            <titel>1984</titel>
            <bild
                src="http://upload.wikimedia.org/wikipedia/en/4/4a/1984_%281956_movie_poster%29.jpg"
                id="cover1984" alt="1984 cover" cover="ja"/>
            <bild
                src="http://3.bp.blogspot.com/-2sVJ5kXGm3M/UzmjHmOyhOI/AAAAAAAACRI/vU-5FQ_Ij6g/s1600/1984-1956-05-g_dia+odi.jpg"
                id="city1984" alt="city 1984" cover="nein"/>
            <mitwirkende>
                <autor drehbuch="William Templeton" buch="George Orwell"/>
                <regie>Michael Anderson</regie>
                <cast>Edmond O'Brien, Michael Redgrave, Jan Sterling, David Kossoff, Mervyn Johns,
                    Donald Pleasence, Carol Wolveridge, Ernest Clark, Patrick Allen, Ronan O'Casey,
                    Michael Ripper, Ewen Solon, Kenneth Griffith</cast>
            </mitwirkende>
            <erscheinungsjahr>1956</erscheinungsjahr>
            <land>Großbritannien, USA</land>
            <inhalt>George Orwell's novel of a totalitarian future society in which a man whose
                daily work is rewriting history tries to rebel by falling in love. </inhalt>
            <länge>90 min</länge>
            <fsk>16</fsk>
            <verfügbarkeit onlineverfügbar="ja">
                <online quelle="http://www.youtube.com/embed/A_Jex2bMwWI">Youtube</online>
            </verfügbarkeit>
        </medium>
    </medien>
    <medien art="film">
        <medium>
            <titel>Fahrenheit 451</titel>
            <bild
                src="http://ia.media-imdb.com/images/M/MV5BMjI3MzI3MjQ2OF5BMl5BanBnXkFtZTgwMTI4ODYxMTE@._V1_.jpg"
                id="coverfahrenheit451" alt="fahrenheit 451 cover" cover="ja"/>
            <bild
                src="http://www.radionoir.it/wp-content/uploads/2014/12/10821857_10205383056124486_990310626_o.jpg"
                id="fahrenheit451" alt="fahrenheit 451 burning books" cover="nein"/>
            <mitwirkende>
                <autor drehbuch="François Truffaut, Jean-Louis Richard" buch="Ray Bradbury"/>
                <regie>François Truffaut</regie>
                <cast>Julie Christie, Oskar Werner, Cyril Cusack, Anton Diffring, Jeremy Spenser,
                    Bee Duffell, Alex Scott</cast>
            </mitwirkende>
            <erscheinungsjahr>1966</erscheinungsjahr>
            <land>Großbritannien</land>
            <inhalt>In an oppressive future, a fireman whose duty is to destroy all books begins to
                question his task.</inhalt>
            <länge>112 min</länge>
            <fsk>12</fsk>
            <verfügbarkeit onlineverfügbar="ja">
                <online quelle="http://www.amazon.de/Fahrenheit-451-Julie-Christie/dp/B00RWBHK4O"
                    >Amazon Prime</online>
                <online quelle="http://www.watchever.de/filme/fahrenheit-451-222142"
                    >Watchever</online>
            </verfügbarkeit>
        </medium>
    </medien>
    <medien art="film">
        <medium>
            <titel>Alphaville</titel>
            <bild
                src="http://ia.media-imdb.com/images/M/MV5BMjE1MDUxNDk2NF5BMl5BanBnXkFtZTgwMDM5MDY5MDE@._V1_SY938_CR12,0,630,938_AL_.jpg"
                id="coveralphaville" alt="alphaville cover" cover="ja"/>
            <bild
                src="https://faqonespionage.files.wordpress.com/2012/07/screen-shot-2012-07-25-at-12-17-22-am.png"
                id="logoalphaville" alt="logo alphaville" cover="nein"/>
            <trailer src="http://www.youtube.com/embed/CzaATgGHmy0" id="traileralphaville"
                name="alphaville trailer" official="nein"/>
            <mitwirkende>
                <autor drehbuch="Jean-Luc Godard"/>
                <regie>Jean-Luc Godard</regie>
                <cast>Eddie Constantine, Anna Karina, Akim Tamiroff</cast>
            </mitwirkende>
            <erscheinungsjahr>1965</erscheinungsjahr>
            <land>Frankreich, Italien</land>
            <inhalt>A U.S. secret agent is sent to the distant space city of Alphaville where he
                must find a missing person and free the city from its tyrannical ruler.</inhalt>
            <länge>99 min</länge>
            <fsk>16</fsk>
            <verfügbarkeit onlineverfügbar="ja">
                <online
                    quelle="https://itunes.apple.com/de/movie/alphaville/id417223290?ign-mpt=uo%3D4"
                    >iTunes</online>
                <online
                    quelle="https://www.videobuster.de/dvd-bluray-verleih/132308/alphavillereferrerzanox2zanpid2006771507585807360"
                    >Videobuster</online>
                <online quelle="https://www.maxdome.de/alphaville-4686940.html">Maxdome</online>
            </verfügbarkeit>
        </medium>
    </medien>
    <medien art="film">
        <medium>
            <titel>La jetée</titel>
            <bild src="http://www.elpelicultista.com/wp-content/uploads/2015/02/el-muelle.jpg"
                id="coverlajetée" alt="lajetée cover" cover="ja"/>
            <bild src="https://rashkphotography.files.wordpress.com/2014/08/vlcsnap-00034.png"
                id="lajetee" alt="la jetee" cover="nein"/>
            <trailer src="http://www.youtube.com/embed/uHyMMffwPUA" id="trailerlajetée"
                name="la jetée trailer" official="nein"/>
            <mitwirkende>
                <autor drehbuch="Chris Marker"/>
                <regie>Chris Marker</regie>
                <cast>Jean Négroni, Hélène Chatelain, Davos Hanich, Jacques Ledoux, André Heinrich,
                    Jacques Branchu, Pierre Joffroy, Étienne Becker, Philbert von Lifchitz, Ligia
                    Branice, Janine Klein, William Klein, Germano Facetti</cast>
            </mitwirkende>
            <erscheinungsjahr>1962</erscheinungsjahr>
            <land>Frankreich</land>
            <inhalt>In a devastated Paris in the aftermath of WWIII, The few surviving humans begin
                researching time travel, hoping to send someone back to the pre-war world for food,
                supplies and maybe a solution to their dire position. One man is haunted by a vague
                childhood memory that will prove fateful.</inhalt>
            <länge>28 min</länge>
            <verfügbarkeit onlineverfügbar="ja">
                <online quelle="https://itunes.apple.com/us/movie/la-jetee/id641178206"
                    >iTunes</online>
            </verfügbarkeit>
        </medium>
    </medien>
    <medien art="film">
        <medium>
            <titel>Traumstadt</titel>
            <bild src="http://ecx.images-amazon.com/images/I/81CI5f71slL.jpg" id="covertraumstadt"
                alt="traumstadt cover" cover="ja"/>
            <trailer src="http://www.youtube.com/embed/rn7k5nY9WJ0" id="trailertraumstadt"
                name="traumstadt trailer" official="nein"/>
            <mitwirkende>
                <autor drehbuch="Rosemarie Fendel" buch="Alfred Kubin"/>
                <regie>Johannes Schaaf</regie>
                <cast>Per Oscarsson, Rosemarie Fendel, Olimpia, Eva Maria Meineke, Helen Vita,
                    Heinrich Schweiger, Rony Williams, Alexander May, Louis Waldon, Josef Hlinomaz,
